### ISSUE TITLE
netbeast cannot run in windows

### ISSUE THREAD

**Issue by vonhust** [netbeast/dashboard#151]
##### 1. Describe your issue ( Expected and actual behaviour )

 I just install the netbeast dashboard through npm install netbeast-cli. 
Then run netbeast, an error coming out.

  Error: spawn UNKNOWN
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:367:9)
    at Object.<anonymous> (C:\Users\wren\Desktop\javascript\node_js\netbeast\node_modules\netbeast-cli\index.js:82:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

It seems  an error is raised in index.js:82:16
  
##### 2. Steps to reproduce the problem
1. npm install netbeast-cli
2. .\node_modules\.bin\netbeast start
  ...

##### 3. Please left us some versioning details like..

    * Where is the dashboard running (OS): Wiindows 7
    * Dashboard version: the latest on 
    * npm & node version: npm 3.7.3,   node 5.9.1
  
  
Thanks, I hope we can figure it out as fast as posible :)

**Comment by jsdario** [comment]
Maybe the problem is related with this one in the forum http://forum.netbeast.co/t/error-while-starting-netbeast-windows/32

I'll try to fix it asap.

Thanks for reporting.

**Comment by jsdario** [comment]
This should fix it https://github.com/netbeast/dashboard/commit/36236735ee8353e3a149055e9d78661133bb32e3

**Comment by fixfinest** [comment]
Thanks **jsdario** That's works, hope to resolve this bug soon #151

**Comment by jsdario** [comment]
Thank you!
