### ISSUE TITLE
Done is not a function

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/dashboard#55]
Sometimes I run the dashboard I get the following error: 

```TypeError: done is not a function
    at Statement.<anonymous> (/Users/luisf/Netbeast/dashboard/src/models/resource.js:25:12)
--> in Database#run('DELETE FROM resources WHERE id = \'41fa9733a4f3e50cda9e1bcfa1be089889f8cc1a\'', [Function])
    at Object.helper.deleteAction (/Users/luisf/Netbeast/dashboard/src/helpers/resource.js:30:6)
    at Resource.destroy (/Users/luisf/Netbeast/dashboard/src/models/resource.js:22:10)
    at /Users/luisf/Netbeast/dashboard/src/models/activity.js:158:18
    at Statement.<anonymous> (/Users/luisf/Netbeast/dashboard/src/models/resource.js:47:12)```

**Comment by jsdario** [comment]
Hopefully it is fixed in next release :)

https://github.com/netbeast/dashboard/commit/2d713d4eec4a839466825584915d3a07fcb221e5

**Comment by luisfpinto** [comment]
Fixed! :+1:
