### ISSUE TITLE
spawn() methods throw an exception on window machine.

### ISSUE THREAD

**Issue by Mo33n** [netbeast/dashboard#88]
```child_process.js:1162
   throw errnoException(err, 'spawn');
         ^
Error: spawn UNKNOWN
   at exports._errnoException (util.js:746:11)
   at ChildProcess.spawn (child_process.js:1162:11)
   at exports.spawn (child_process.js:995:9)
   at Object.<anonymous> (D:\netBeast Github\dashboard\index.js:65:11)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Function.Module.runMain (module.js:501:10)
   at startup (node.js:129:16)
   at node.js:814:3
```

**Comment by jsdario** [comment]
It targets this line https://github.com/netbeast/dashboard/blob/master/index.js#L65
The error `UNKOWN` does not show us much about the reasons, but maybe changing the deamon to a same-process task (as in `src/services/scanner`) might do the trick.

**Comment by luisfpinto** [comment]
Bug solved https://github.com/netbeast/dashboard/pull/89
